### PR TITLE
feat: modify for custom CA certificates

### PR DESCRIPTION
**Pull request by olevski**
Allows the core service to properly access another service (i.e. namely gitlab) if that service is using self-signed certificates.

I followed the Gitlab cloud native helm chart and how they tackle this issue when addressing this. See for examples:
- https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/templates/_certificates.tpl
- https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/charts/gitlab/charts/webservice/templates/deployment.yaml#L102

Fixes https://github.com/swissdatasciencecenter/renku/issues/2324

/deploy #persist

### CODE REVIEW

**Comment by Panaetius** [comment]
What's the state of this PR? @olevski

**Comment by olevski** [comment]
@Panaetius this is still relevant but it can only be merged after https://github.com/SwissDataScienceCenter/renku/pull/2329

**Comment by Panaetius** [comment]
@olevski Do we have an ETA on that? It's also been open a while :slightly_smiling_face:

**Comment by olevski** [comment]
> @olevski Do we have an ETA on that? It's also been open a while 🙂

@Panaetius the review of some of the changes that this PR depends on is a bit stalled. So when that PR is reviewed this can be merged. I think that maybe in a week or two. I will bring this up to speed and resolve conflicts when it is ready for you to review. I have not forgotten about it.

**Comment by olevski** [comment]
The blocking, dependent PRs have been resolved. This is ready for review.

**Review by Panaetius — DISMISSED** [review]
Thank you!

**Comment by olevski** [comment]
Please do not merge this. It seems that there is most like a problem with the acceptance tests but I want to confirm before ignoring the acceptance tests.

**Comment by Panaetius** [comment]
You should merge to develop anyways, not master

**Comment by olevski** [comment]
@Panaetius this is ready now. The acceptance tests finally pass. I wanted to see this before merging earlier. I had to dismiss your approval to resolve conflicts on updating the PR.

**Review by Panaetius — APPROVED** [review]

**Pull request merged**
