### PR TITLE
test(service): support more cases for project_name

### PR DESCRIPTION
**Pull request by jsam**

### CODE REVIEW

**Review by lorenzo-cavazzi — APPROVED** [review]
Works well now! :rocket: 

If anyone wants to try a preview: https://lorenzotest.dev.renku.ch/projects/new

**Comment by rokroskar** [comment]
So we're just removing non-ascii characters and replacing them with `-`? Not doing character translation?

**Comment by jsam** [comment]
@rokroskar Yes. We are doing exactly the same as GitLab does when you create a new project.

**Review by lorenzo-cavazzi — APPROVED** [review]
I tested this a bit while developing the UI side SwissDataScienceCenter/renku-ui#1115 and it works well :+1: 

It's currently used in this UI preview: https://lorenzotest.dev.renku.ch/

**Review by mohammad-sdsc — APPROVED** [review]
Thanks 🚀

**Pull request merged**
