### PR TITLE
ci: include AppVeyor configuration

### PR DESCRIPTION
**Pull request by jirikuncar**
Run tests on Windows.

### CODE REVIEW

**Comment by rokroskar** [comment]
@jirikuncar is this still being worked on?

**Comment by jirikuncar** [comment]
@rokroskar the AppVeyron is working - however renku tests do not run on Windows.

**Comment by rokroskar** [comment]
This PR then seems like it might be open indefinitely - or is there a clear way forward?

**Comment by jirikuncar** [comment]
@rokroskar it mostly about paths - `\` vs `/`

**Comment by rokroskar** [comment]
Is it that the tests fail on windows or that renku doesn't run on windows? Do we need to support windows atm?

**Comment by jsam** [comment]
Progress bars with multiprocessing act differently on Windows shell as well so it would be nice to have this (if we have any windows users and promised support for windows platform already). If there is no promised Windows compatibility, we should close this until we do.

**Comment by rokroskar** [comment]
I don't recall us having any requests for windows compatibility - am I wrong about this @jirikuncar?

**Pull request closed without merging**
