### PR TITLE
chore(docs): add spellcheck

### PR DESCRIPTION
**Pull request by rokroskar**
Adds spellcheck to the docs test.

### CODE REVIEW

**Review by Panaetius — APPROVED** [review]
Tihs looks graet, tahnk you!

[edit]
I guess it's `parametrization` not `parameterization`

**Comment by rokroskar** [comment]
😭 

I think I fixed that one before?

**Comment by rokroskar** [comment]
Ah no now I remember - that was the commit that made me open this PR in the first place because it broke the docs build in the renku repo 😄

**Review by Panaetius — APPROVED** [review]
Aewsmoe!

**Comment by rokroskar** [comment]
> Aewsmoe!

This will no longer be tolerated around here @Panaetius! 🤣

**Comment by Panaetius** [comment]
We'll, you should really just implement spellcheckng for commentsd and PR titles as well, as those'l end up in the changelog.

**Comment by rokroskar** [comment]
I leave these maintainer tasks to the maintainers 😉

**Pull request merged**
