### PR TITLE
chore: fix coveralls comments

### PR DESCRIPTION
**Pull request by Panaetius**
Coveralls should be posting code coverage on the repo, but doesn't I think it's because the actions only run on push, not on PR. So from the POV of coveralls, it's never run on a PR and doesn't comment. This should fix that.

### CODE REVIEW

**Comment by olevski** [comment]
@Panaetius so we should see a comment on this PR that shows the test coverage? If the fix works.

**Comment by Panaetius** [comment]
> @Panaetius so we should see a comment on this PR that shows the test coverage? If the fix works.

Well, since it doesn't change code, I'm not sure. But this is the last thing I could think of why it's not writing those comments.

**Comment by Panaetius** [comment]
Oh there it is

**Review by olevski — DISMISSED** [review]
This is great! I thought you were supposed to dig through the actions logs to see the coverage.

**Review by olevski — APPROVED** [review]

**Pull request merged**
