### PR TITLE
chore: RFC-001 workflow ux

### PR DESCRIPTION
**Pull request by Panaetius**
RFC for new workflow commands to improve user experience.

### CODE REVIEW

**Comment by rokroskar** [comment]
Is the plan to merge this and then carry on discussion [here](https://github.com/SwissDataScienceCenter/renku-python/discussions/categories/request-for-comment)?

**Comment by Panaetius** [comment]
No the plan is to discuss it and to change it here, until we decide to accept the RFC, then merge it (otherwise we need to make a PR each time we want to edit it). We can discuss it there, though, while the PR is open

**Comment by jachro** [comment]
After some checks on both sides it looks we the prov#hadRole we currently have on both Usage and Generation is not really used anymore. Let's drop it then :)

**Comment by Panaetius** [comment]
> should Dataset Part's @id be extending Dataset's @id; currently, it doesn't extend;
>should PublicationEvent has @id like this: https://localhost/datasettags/1.0%40e732668c4eeec0ddd8871290f9484e68605c0048 or https://renku-host/datasettags/1.0%40e732668c4eeec0ddd8871290f9484e68605c0048

I think we could discuss this in a separate issue, as this RFC is on regards to workflows.

> should DatasetProvenance be a blank node? It is at the moment 
We won't use the single-file DatasetProvenance in the future as it didn't work out, and stick with the current format (or something very close to it).

> should Entity has the isPartOf property pointing to the project? It's a no-brainer but we're missing the property now
We're slowly moving away from having every node point to the project it is in, as this gets complicated, especially with flattened jsonld. E.g. if a projects `agent` changes, and you reuse an entity, now you have entities pointing to the same project node but with differing properties, which need to be then merged in some way. Ideally we'd only like to have top-level nodes point to the project (Dataset, Plan, Activity) to simplify things. I've updated the docs accordingly but it's certainly up for discussion.

**Comment by jachro** [comment]
@Panaetius I updated my comment according to the latest discussion.

**Comment by schymans** [comment]
I am looking at this file: https://github.com/SwissDataScienceCenter/renku-python/blob/rfc-001-workflow-ux/design/001-new-workflow-commands/001-new-workflow-commands.md

I see this for the first time, so sorry if my input below is useless due to lack of understanding. Just ignore it if this is the case.

The description starts with a specific workflow ID, but I wonder how to get the workflow IDs relevant for a specific file, e.g. where file `data.csv` was either created or used as input, and then how to extract the respective `renku run` command used to generate that workflow. As stated, the `renku run` commands can be quite complex, so it would be nice to copy a previous one and adapt for a new use case. 

Another question, how does `renku dataset add` integrate into the workflow ecosystem? One of the examples given above includes:
`$ renku run --name download-data --description "Downloads the daily data csv" --output datafile="data.{%Y-%m-%d}.csv" -- bash download.sh`
But I guess that the above would not add `data.{%Y-%m-%d}.csv` as a dataset unless `download.sh` has a command `renku dataset add` in it. Generally, I would like to preserve the link to the origin of the data, but I don't see how this is done in this example.

**Comment by Panaetius** [comment]
@schymans In regards to how datasets figure into this, we decided to not design this in this RFC, but rather as a followup, as it's already complex enough. So we also don't know yet how datasets integrate into the workflow ecosystem (though we have some ideas). We discussed in the past that a run can automatically put files into a dataset or that a dataset can be specified as input and then path of the command are relative to the dataset, but there's many details and edge cases that we haven't settled on yet (Can a command produce more than 1 dataset, what happens if the command is used as part of a larger command, can a dataset be used that isn't in the current project, to just name a few open questions).

A python script could specify the URL as a parameter using https://renku.discourse.group/t/renku-python-api/340 so it's not hidden inside the script, so that would be a workaround in this case. Though it wouldn't track any information about whats in the URL like a checksum, just the URL itself. Same if you did `renku run -- curl http://...`.
Adding the file to a dataset by URL should preserve it's provenance with the current implementation. There has been discussion of adding a file to a repo by URL with tracking provenance but outside of a dataset, https://github.com/SwissDataScienceCenter/renku-python/issues/1737 and https://github.com/SwissDataScienceCenter/renku-python/issues/671 (I guess you know about this one :slightly_smiling_face: ), but this will have to wait until we've done the switch to new metadata (we need #1737 for that).

As for the other question, the intention is that `renku workflow history` allows showing executions of template by some filters. Not this could be a workflow ID or a file, or something else. But as I mentioned in the meeting this morning, that is the command that is least defined so far, just that it should behave similar to a `git log` in look and feel. The command itself is definitely useful, but not integral to how the new workflow system works, so not much time was spent discussing it and it's left to whoever implements it to come up with a good design. Here we'd be really grateful if the community could provide use case/examples of what they'd like it to do, so we can take those into account.

**Review by vigsterkr — APPROVED** [review]

**Comment by schymans** [comment]
Thanks for the explanation, @Panaetius. Where would be the best place to continue this discussion? From a user's perspective, I would love to be able to click on an input file in the KG and see the command how it was imported into the repo, and if it was important from an external source, to follow the link and see if there are any updates on the external site that might make it worthwhile to update the version of the file I am using.

**Pull request merged**
