### PR TITLE
feat(core): Adds communication util to decouple click from core

### LINKED ISSUE #737: Decouple communication between presentation layer (CLI/Service) and renku core
In #702 dataset import/export click dependencies were removed from `renku.core` code, by using callbacks and otherwise injecting the relevant code into the business layer.

This works, but can get a bit unwieldy, especially since many of the callbacks are still somewhat `click`-specific and the interface might not be applicable for other potential consumers of `core`. Additionally, each method has it's own callbacks that sometimes differ from other functions' callbacks, making them still conceptually tightly coupled.

Basically, the refactoring we did with the `cli`, `core` namespaces means our application now has a rather traditional `presentation`, `logic` and potentially `DAL` layered architecture, so we should follow patterns that make sense to decouple `presentation` from `logic`.

Something like the mediator pattern or event based communication could work well.

As this should be unified for all functions (not each having its own slightly different implementation), it needs some architecture work and is not done in #702

### PR DESCRIPTION
**Pull request by Panaetius**
adds `renku.core.utils.communication` namespace that can be used to return messages (e.g. `click` ones for the CLI) without having to pass things around everywhere and without any coupling/dependencies.

Closes #737 

WIP: Needs to be added everywhere, Service needs its own implementation

### CODE REVIEW

**Comment by jsam** [comment]
Ok, I thought about it over coffee and I think what we could do is the following. We keep this proposal under the hood for easier management and just update the API part.

So instead of the:
```
with chdir(project.abs_path):
  with service_callback_communication(user_job):
      import_dataset(...)
```

we could have something like:

```
```
with project(path) as my_project:    # this should under the hood chdir to the cwd and create project context manager
  my_project.attach_output(stdout)   # logs to the stdout as they happend (mainly for CLI usage) and it could be ommited completely
  
  result = import_dataset(...)
  if my_project.warnings:
    pass # handle warnings
   
 ```
```

**Comment by Panaetius** [comment]
I think that would be a workable and clean solution :+1: Also curious about what @mohammad-sdsc and @rokroskar have to say.

**Comment by rokroskar** [comment]
I like the suggestion from @jsam - the only thing we need to make sure is that the user using renku-python as an SDK shouldn't need to do much to get a sensible default (i.e. messages and errors going to stdout/stderr). I think calling `attach_output` is already too much :)

**Comment by Panaetius** [comment]
We can make stdout/stderr the default if no other listener is set

**Comment by jsam** [comment]
I'm not really convinced that stdout should be default since 2 out of 3 use cases would need to have it disabled from stdout.

`my_project.attach_output(stdout)` is an optional configurable parameter for the cases where continuous output makes sense (as it is in CLI), in the SDK usage and the service we don't want this since it would just pollute the standard output so having control over this in those cases makes a lot of sense to me.

Internal communications should be disabled as default, and if the user wants to peek into it it should opt-in for such behaviour.

**Comment by Panaetius** [comment]
> I'm not really convinced that stdout should be default since 2 out of 3 use cases would need to have it disabled from stdout.
> 
> `my_project.attach_output(stdout)` is an optional configurable parameter for the cases where continuous output makes sense (as it is in CLI), in the SDK usage and the service we don't want this since it would just pollute the standard output so having control over this in those cases makes a lot of sense to me.
> 
> IMHO, internal communications (output to stdout) should be disabled as default, and if the user wants to peek into it (via stdout) it should opt-in for such behaviour.
> 
> The way I see it that makes sense to me is, core module should always propagate exceptions to the top-level API and not just log them internally to stderr so the user of the core module can handle them correctly and the way he wants. Now if we talk about the CLI, on the other hand, I do agree that sensible defaults of stdout and stderr should be there since that is the best practice to do so.

Right now communication is disabled by default.

I'll still add an stdout/stderr implementation so someone using it as an SDK could easily enable the output without click stuff.

This is mainly about warnings/info and I don't intend to get rid of exceptions, they should still be raised in core, as you said.

**Comment by Panaetius** [comment]
I changed it a bit. The way it works right now:
- Exceptions work as before and are untouched by this, so nothing changes execution flow in that area
- If you just use `renku.core` by itself, no warnings/infos get logged anywhere. You can do `communication.subscribe(StandardOutput())` somewhere to enable logging to stdout.
- If you use the CLI, you don't have to do anything. Click communication strategy is available/injected automatically in all CLI commands.
- In the service things are a bit more difficult since we need the user_job. But as seen here https://github.com/SwissDataScienceCenter/renku-python/blob/25ae5406f7227d1198b52ca4c06f83f1399c7599/renku/service/jobs/datasets.py#L42 there's now just a `ProjectContext` that does some stuff, and if you want to do something with logged messages, you have them available in `ctx.callback.infos`, `ctx.callback.warnings` and you can do whatever you want with those.

**Comment by Panaetius** [comment]
Closing in favor of https://github.com/SwissDataScienceCenter/renku-python/pull/1744

**Pull request closed without merging**
