### PR TITLE
Snap libxml2

### PR DESCRIPTION
**Pull request by jirikuncar**
# Description

Fixes issues with building Snap packages.

## Type of change

Please select relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have read and understood the **CONTRIBUTING** document.
- [x] I have performed a self-review of my own code.
- [x] I have signed and sent the [CLA document]
      (https://github.com/SwissDataScienceCenter/documentation/wiki/files/SDSC_Contributor_License_Agreement_v1.0.pdf).
- [ ] I have added tests to cover my changes.
- [ ] I have **NOT** removed any existing tests.
- [ ] I have updated the documentation accordingly.
- [ ] I have described *all* changes in the **CHANGELOG.rst**.
- [ ] I have run ``./run-tests.sh`` locally.

### CODE REVIEW

**Comment by jirikuncar** [comment]
@leafty have you managed to build the snap locally?

**Comment by leafty** [comment]
it builds something, can't say that one works yet

**Comment by rokroskar** [comment]
I thought we've given up on using snaps?

**Comment by rokroskar** [comment]
I'm closing this for now - don't think we are currently supporting snaps.

**Pull request closed without merging**
