### PR TITLE
feat(cli): support template and docker migration

### LINKED ISSUE #1860: Enable Dockerfile and template update in the cli
Now that the service has support to update the renku version in the dockerfile and to update the template, we should add support for it in the CLI as well.

We should add flags for it to `renku migrate`, but the default should probably still be to only migrate metadata (Or we should prompt the user). Additionally, we should also add `check_migration` support on the CLI.

### PR DESCRIPTION
**Pull request by Panaetius**
closes #1860

### CODE REVIEW

**Review by rokroskar — CHANGES_REQUESTED** [review]
Thanks @Panaetius this is going to be a useful feature! I can't quite get it to work yet... so here is what I tried:

* in my local clone of the template repo, make a branch that is a few commits behind master
* initialize my project with `renku init -s file://<path-to-template-repo> -r test-branch test-template-update`
* move the tip of `test-branch` in the local template repo to `master` i.e. a few commits ahead - presumably `renku migrate` should now offer to update the template
* run `renku migrate -c` in the project - I get `Info: The Dockerfile refers to an older version of renku and can be updated using 'renku migrate'.` 
* running `renku migrate` doesn't seem to do anything

Not sure what to make of it?

**Review by rokroskar — APPROVED** [review]
this works now :) 

There is the wording suggestion still left, but if you disagree feel free to disregard.

**Comment by Panaetius** [comment]
Also added some docs

**Review by rokroskar — APPROVED** [review]
🥇

**Pull request merged**
