### PR TITLE
Login to renkulab through CLI

### PR DESCRIPTION
**Pull request by ableuler**
Revival of #193, see the original PR for details about the current status.

### CODE REVIEW

**Comment by jsam** [comment]
I wonder if we should tackle #983 before merging this one. The way I see it this would add additional vertical to it, which would be:

```
pip install renku[lab]
```

**Comment by ableuler** [comment]
> I wonder if we should tackle #983 before merging this one

Sounds reasonable to me. This issue isn't terribly urgent.

**Comment by rokroskar** [comment]
It seems like this might have to be a pretty manual merge... the underlying code is completely changed afaict.

**Comment by jsam** [comment]
I think we should close this PR. Any objections against it?

**Comment by rokroskar** [comment]
I think the general idea is right, but the code is so different now that a rebase would be pretty difficult.

**Comment by ableuler** [comment]
I just wanted to make sure we still have @ebiiii's code around once we finally tackle this issue. I think many of the problems he has solved back then are independent of the rest of the renku-python codebase (ie the whole interaction with the browser). Closing the PR but keeping the branch around and mentioning it in #1242 is fine for me.

**Pull request closed without merging**
