### PR TITLE
cli: support rerun with editable inputs

### LINKED ISSUE #97: cli: rerun with different parameters
enable this:

```
$ renga runner rerun --job job.yml .renga/workflow/step12345.cwl 
```

### PR DESCRIPTION
**Pull request by jirikuncar**
(closes #97)

### CODE REVIEW

**Comment by rokroskar** [comment]
I'm trying to understand what the intended functionality here is.

* I've tried `renku rerun --show-inputs <path>` and I expected that this would just display which inputs are needed to recreate `<path>` but instead it actually executed the rerun. 
* I also tried `renku rerun --edit-inputs input_1=whatever <path>` but this seemed to not be the correct syntax. 
* `renku rerun --edit-inputs <path>` yields `KeyError: 'step_1/output_stdout'`

**Comment by jirikuncar** [comment]
@rokroskar it's a first minimal implementation, hence there still might be some limitations.

1. I added `--default-inputs` switch which does "nothing". `--show-inputs` displays inputs and exits.
2. `--edit-inputs` will prompt for input argument. It is not possible to pass the input arguments as parameters yet.
3. I need more details - traceback and packed repo would be nice.

**Comment by rokroskar** [comment]
Here's what I did: 

```
$ renku init
$ renku run echo "woop" > woop.out
$ renku rerun --show-inputs woop.out
# Inputs:
input_1: 'woop'
Resolved '.renku/workflow/e8bcf80c095e44ed86ddaa6937c83428.cwl' to 'file:///private/tmp/test-97/.renku/workflow/e8bcf80c095e44ed86ddaa6937c83428.cwl'
[workflow e8bcf80c095e44ed86ddaa6937c83428.cwl] start
[step step_1] start
[job step_1] /private/var/folders/wz/myhc0xj14n5585p3mmqhdn_c0000gn/T/tmpl47lzm5t$ echo \
    woop > /private/var/folders/wz/myhc0xj14n5585p3mmqhdn_c0000gn/T/tmpl47lzm5t/woop.out
[job step_1] completed success
[step step_1] completed success
[workflow e8bcf80c095e44ed86ddaa6937c83428.cwl] completed success
Moving outputs  [                                    ]  1/1
Unchanged files:

        woop.out
```

Looks like this actually ran the step again instead of just showing the inputs?

**Comment by jirikuncar** [comment]
@rokroskar have you checked the latest version? I have even added a test for that situation.

**Pull request merged**
