### PR TITLE
feat(core): add shell_complete implementation for workflows and datasets

### PR DESCRIPTION
**Pull request by vigsterkr**
# Description

Using the feature of [click's auto-complete implementation](https://click.palletsprojects.com/en/8.0.x/shell-completion/) when 
 - running various `renku dataset` sub-commands the actual dataset name can be auto-completed
 - running various `renku workflow` sub-commands the actual workflow name can be auto-completed

- [x] fix dependency injection
- [x] Mention in the documentation how to activate for bash, zsh or fish (basically the shells that are supported by click)  auto-completion of renku commands

### CODE REVIEW

**Comment by vigsterkr** [comment]
currently with this implementation there's a problem with dependency injection, namely:

```
File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/bin/renku", line 8, in <module>
    sys.exit(cli())workflow details.
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/renku/cli/exception_handler.py", line 123, in main
    result = super().main(*args, **kwargs)ing through a...
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/renku/cli/exception_handler.py", line 89, in main
    return super().main(*args, **kwargs) by workflows.
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/click/core.py", line 1057, in main
    self._main_shell_completion(extra, prog_name, complete_var)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/click/core.py", line 1132, in _main_shell_completion
    rv = shell_complete(self, ctx_args, prog_name, complete_var, instruction)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/click/shell_completion.py", line 49, in shell_complete
    echo(comp.complete())
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/click/shell_completion.py", line 291, in complete
    completions = self.get_completions(args, incomplete)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/click/shell_completion.py", line 273, in get_completions
    return obj.shell_complete(ctx, incomplete)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/click/core.py", line 2401, in shell_complete
    results = self._custom_shell_complete(ctx, self, incomplete)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/renku/cli/workflow.py", line 564, in _complete_workflows
    return list(filter(lambda x: x.startswith(incomplete), search_workflows(starts_with=incomplete)))
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/inject/__init__.py", line 339, in injection_wrapper
    kwargs[param] = instance(cls)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/inject/__init__.py", line 402, in instance
    return get_injector_or_die().get_instance(cls)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/renku/lib/python3.9/site-packages/renku/core/management/command_builder/command.py", line 60, in _patched_get_injector_or_die
    raise inject.InjectorException("No injector is configured")
inject.InjectorException: No injector is configured
```

**Comment by vigsterkr** [comment]
other than that using `eval "$(_RENKU_COMPLETE=zsh_source renku)"` for `zsh` is working pretty great.

**Review by mohammad-sdsc — COMMENTED** [review]
This is a very cool feature! Thanks Viktor! I've used it and have the following comments:
* It prevents shell completion from working. For example, if I type `renku dataset add my-dataset <TAB>` to get a list of paths, nothing shows up; instead, it seems that Renku completions is called again. I believe disabling shell completions is not desirable.
* Installation could be made easier: There is a `renku --install-completion` command that uses `click-completion` package to install the completion. Maybe you can check to see what it does and if it's useful here.

**Comment by vigsterkr** [comment]
thanks for the feedback! see my answers below

>     * It prevents shell completion from working. For example, if I type `renku dataset add my-dataset <TAB>` to get a list of paths, nothing shows up; instead, it seems that Renku completions is called again. I believe disabling shell completions is not desirable.

good catch! this is indeed not good! i've just checked a bit into this. It's actually because of the following reason: the `dataset add` command `click.argument` for `urls` has no type parameter, that's why click doesn't know how to autocomplete it. in other words:
```
-@click.argument("urls", nargs=-1)
+@click.argument("urls", type=click.Path(exists=True), nargs=-1)
```
would actually fix the problem. now of course this is semantically not what we want but in this specific case i think it solves our problem. because anyways there would be no sane way to autocomplete a proper url, like `http://`. or?

>     * Installation could be made easier: There is a `renku --install-completion` command that uses `click-completion` package to install the completion. Maybe you can check to see what it does and if it's useful here.

oh i didn't know about this 🤦 i've just quickly checked and it's not really working for me, but i'll investigate and try to make the whole shell integration installation working with this command and add it to this patch

**Comment by vigsterkr** [comment]
@mohammad-sdsc so i've looked into the whole `--install-completion` command, which uses https://github.com/click-contrib/click-completion. basically with click 8.0 it is broken, see https://github.com/click-contrib/click-completion/issues/41 and for example in AiiDA they already dropped the dependency: https://github.com/aiidateam/aiida-core/issues/5098

i'd do the same, but we could still keep the command that actually expands the shell's config file with the right command (see the how-to) if we wanna maintain that code-base 🙃

**Review by mohammad-sdsc — APPROVED** [review]
Works great! Thank you!

**Pull request merged**
