### PR TITLE
build(deps): update dependencies

### PR DESCRIPTION
**Pull request by Panaetius**
Update dependencies to newest version.

### CODE REVIEW

**Review by vigsterkr — APPROVED** [review]
📦 🚀

**Comment by Panaetius** [comment]
Sorry, Dependabot just doesn't want to stop. I miss the times when it was broken :cry:

**Review by vigsterkr — DISMISSED** [review]

**Comment by vigsterkr** [comment]
mmm the `cwltool==3.1.20220210171524` update went through it seems :( unfortunately since it generates a warning on the stdout, this results a pytest failure for all `tests/cli/test_workflow.py` tests. either i need to refactor those tests, or (which i suggested in the cwltool update PR) would rather keep the pinned version of `cwltool` that's coming from `toil==5.6.0`

**Review by vigsterkr — APPROVED** [review]
🚀

**Pull request merged**
